--CREATE 
ALTER
PROC USP_21424069_READ_DATA_USERS_FIX
AS
BEGIN TRAN
	BEGIN TRY

	DECLARE @COUNT_STAFF INT = (SELECT COUNT(*) FROM Users U with(holdlock) WHERE U.RoleID = 2)

	WAITFOR DELAY '0:0:10'
	
	SELECT * FROM Users U WHERE U.RoleID = 2

	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1	
	END CATCH
COMMIT TRAN
RETURN 0
GO
