CREATE PROC SP_21424057_Transfer1
	@OrderID AS INT, @DiverID AS INT
AS
BEGIN TRAN
	BEGIN TRY
		IF EXISTS (SELECT * FROM Orders WHERE ID = @OrderID AND Status = 1 AND (DriverID IS NULL OR DriverID = ''))
		BEGIN
			WAITFOR DELAY '0:0:05'
			UPDATE Orders
			SET Status = 2, DriverID = @DiverID
			WHERE ID = @OrderID
			WAITFOR DELAY '0:0:05'
		END
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO
CREATE PROC SP_21424057_Transfer2
	@OrderID AS INT, @DiverID AS INT
AS
BEGIN TRAN
	BEGIN TRY
		IF EXISTS (SELECT * FROM Orders WHERE ID = @OrderID AND Status = 1 AND (DriverID IS NULL OR DriverID = ''))
		BEGIN
			WAITFOR DELAY '0:0:05'
			UPDATE Orders
			SET Status = 2, DriverID = @DiverID
			WHERE ID = @OrderID 
		END
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0