CREATE 
--ALTER
PROC USP_21424032_DIRTY_UPDATE_Fix
	@ORDERS_ID BIGINT,
	@PRODUCT_ID BIGINT,
	@QUANTITY INT,
	@PRICE DECIMAL(18,2),
	@AMOUNT DECIMAL(18,2)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT *
					FROM Orders O
					WHERE O.ID = @ORDERS_ID)
		BEGIN
			PRINT N' ĐƠN HÀNG KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 1
		END
		
		INSERT OrderDetails
		VALUES(@ORDERS_ID, @PRODUCT_ID, @QUANTITY, @PRICE, @AMOUNT)

		declare @total_Amount decimal(18,2)
		set @total_Amount = (select SUM(od.Amount) from OrderDetails od where od.OrderID = @ORDERS_ID)

		update Orders 
		set Amount = @total_Amount 
		where ID = @ORDERS_ID

		--ĐỂ TEST
		WAITFOR DELAY '0:0:08'
		ROLLBACK TRAN 
		RETURN 1
		-----
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

CREATE 
--ALTER
PROC USP_21424032_DIRTY_READ_Fix
	@ORDERS_ID BIGINT,
	@TONGTIEN DECIMAL(18,2) OUT
AS
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * 
					FROM Orders 
					WHERE ID = @ORDERS_ID)
		BEGIN
			PRINT N'ĐƠN HÀNG KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 
		END
		
		SET @TONGTIEN = (SELECT Amount FROM Orders WHERE ID = @ORDERS_ID)


	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO