//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAndDelivery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBranch
    {
        public long ID { get; set; }
        public long BranchID { get; set; }
        public long ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Product Product { get; set; }
    }
}
