//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAndDelivery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Branches = new HashSet<Branch>();
            this.Contracts = new HashSet<Contract>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
        }
    
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Representative { get; set; }
        public string Identity { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> District { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> NumBranch { get; set; }
        public string NameOfBank { get; set; }
        public string BankAccount { get; set; }
        public int NumOfOrder { get; set; }
        public Nullable<int> TypeTransferID { get; set; }
        public string LicensePlates { get; set; }
        public Nullable<long> RoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual Role Role { get; set; }
    }
}
